image: alpine/edge
packages:
  - build-base
  - cmake
  - clang19-extra-tools
secrets:
  - ca99d209-296a-41b7-9eda-454250e4b901
environment:
  REPO: fsm
sources:
  - https://git.sr.ht/~ekoeppen/fsm
  - https://git.sr.ht/~ekoeppen/build-scripts
tasks:
  - build: |
      cd $REPO
      cmake -B build -S .
      cmake --build build
  - lint: ./build-scripts/clang-lint clang-format $REPO include
  - test: |
      cd $REPO
      ./build/fsm_test
  - mirror-to-github: ./build-scripts/github-mirror $REPO
